check50:
  checks:
    hello world:
      - run: python3 hello.py # run python3 hello.py
        stdout: Hello, world! # expect Hello, world! in stdout
        exit: 0 # expect program to exit with exitcode 0
    foo:
      - run: python3 foo.py
        stdin: baz
        stdout: baz
        exit: 0
    bar:
      - run: python3 bar.py
        stdin: baz
        stdout: bar baz 
      - run: python3 bar.py
        stdin:
          - baz
          - qux
        stdout:
          - bar baz
          - bar qux
